name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4

      - name: Update recent activity
        uses: avinal/Profile-Readme-Activity@main
        with:
          GITHUB_USERNAME: GenCabMon
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
