name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4
      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.5.0
        with:
          GH_USERNAME: GenCabMon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
